/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

// Gradle 플러그인 설정 블록
plugins {
    // Kotlin JVM 프로젝트로 설정 (버전은 현재 설치된 Kotlin과 맞춰줌)
    kotlin("jvm") version "1.9.23"

    // 애플리케이션으로 실행 가능하게 해주는 플러그인
    application
}

// 애플리케이션 진입점(Main 클래스) 지정
application {
    // 컴파일 후 실행할 main 함수가 포함된 클래스 파일 이름 (Main.kt 기준)
    mainClass.set("MainKt")
}

// 외부 라이브러리를 받을 저장소 설정
repositories {
    // 가장 일반적인 중앙 저장소로, 오픈소스 라이브러리를 여기서 가져옴
    mavenCentral()
}

// 프로젝트에 사용할 의존성(라이브러리) 설정
dependencies {
    // Ktor의 핵심 서버 기능 (라우팅, 요청 처리 등)
    implementation("io.ktor:ktor-server-core:2.3.3")

    // 실제 HTTP 서버로 실행하기 위한 엔진(Netty 기반)
    implementation("io.ktor:ktor-server-netty:2.3.3")

    // JSON 등 데이터를 직렬화하고 요청/응답을 처리할 수 있는 플러그인
    implementation("io.ktor:ktor-server-content-negotiation:2.3.3")

    // JSON 처리를 위한 직렬화 방식으로 Gson 사용 (Ktor에서 자동 변환)
    implementation("io.ktor:ktor-serialization-gson:2.3.3")

    // 서버 실행 시 로그를 출력하기 위한 로깅 프레임워크 (필수는 아니지만 유용함)
    implementation("ch.qos.logback:logback-classic:1.2.11")
}
